import { Activity, CircleAlert, RadioTower, Thermometer, WifiOff } from 'lucide-react'
import { shelves } from '../../data/shelves'
import { useSimulationStore } from '../../stores/simulationStore'

export function ShelfSensors({ compact = false }: { compact?: boolean }) {
  const events = useSimulationStore((state) => state.events)
  const latestFor = (shelfId: string) => [...events].reverse().find((event) => event.shelfId === shelfId && (event.source === 'SHELF_SIMULATOR' || event.type === 'AUTOMATIC_CHECKOUT_DISABLED'))
  return <div className={`sensor-panel ${compact ? 'compact' : ''}`}><div className="panel-heading"><div><div className="panel-kicker"><RadioTower size={13} /> Smart shelves</div><h3>Physical signal health</h3></div><span className="simulated-label">SIMULATED</span></div><div className="sensor-list">{shelves.map((shelf) => { const event = latestFor(shelf.id); const offline = event?.type === 'SENSOR_UNAVAILABLE' || event?.type === 'AUTOMATIC_CHECKOUT_DISABLED'; const moved = event?.type === 'SHELF_WEIGHT_DECREASED'; const delta = moved ? -Number(event?.payload.quantity ?? 1) * 0.42 : event?.type === 'SHELF_WEIGHT_RESTORED' ? 0 : 0; const current = shelf.baselineWeight + delta; return <div className="sensor-row" key={shelf.id}><div className={`sensor-state ${offline ? 'offline' : moved ? 'moving' : 'online'}`}>{offline ? <WifiOff size={14} /> : moved ? <Activity size={14} /> : <RadioTower size={14} />}</div><div className="sensor-main"><div className="sensor-title"><strong>{shelf.id.replace('-', ' ').toUpperCase()}</strong><span>{offline ? 'OFFLINE' : moved ? 'ITEM REMOVED' : 'STABLE'}</span></div><div className="sensor-bar"><i style={{ width: `${Math.max(5, Math.min(100, current / shelf.baselineWeight * 100))}%` }} /></div><div className="sensor-meta"><span>Base {shelf.baselineWeight.toFixed(2)} kg</span><span>Now {current.toFixed(2)} kg</span><span className={offline ? 'bad' : 'good'}>{offline ? '0%' : `${Math.round((event?.confidence ?? 0.95) * 100)}%`}</span></div></div><button className="sensor-info" title="Sensor detail"><Thermometer size={13} /></button></div> })}</div>{!compact && <div className="sensor-foot"><CircleAlert size={13} /><span>Weight deltas identify movement, not intent or exact attribution.</span></div>}</div>
}
