import { Activity, AlertTriangle, ArrowRight, Camera, CircleCheck, ClipboardList, Gauge, Play, Radio, RefreshCw, ShieldCheck, Timer, Users } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { PageHeader, SectionHeading } from '../components/layout/AppShell'
import { MetricCard } from '../components/common/MetricCard'
import { EmptyState } from '../components/common/EmptyState'
import { StatusPill } from '../components/common/StatusPill'
import { EventTimeline } from '../components/timeline/EventTimeline'
import { VirtualCart } from '../components/cart/VirtualCart'
import { CameraFeed } from '../components/camera/CameraFeed'
import { ShelfSensors } from '../components/sensors/ShelfSensors'
import { SimulationControls } from '../components/simulation/SimulationControls'
import { useSimulationStore } from '../stores/simulationStore'
import { useSettingsStore } from '../stores/settingsStore'

export function DashboardPage() {
  const navigate = useNavigate()
  const { events, scenario, status, result, session } = useSimulationStore()
  const setSettings = useSettingsStore((state) => state.set)
  const active = events.length > 0 || status === 'RUNNING' || status === 'PAUSED' || status === 'COMPLETE'
  const confirmed = result?.itemResults.filter((item) => item.status === 'CONFIRMED').length ?? 0
  const provisional = result?.itemResults.filter((item) => ['PROVISIONAL', 'UNVERIFIED', 'CAMERA_UNCERTAIN'].includes(item.status)).length ?? 0
  const openExceptions = result?.itemResults.filter((item) => !['CONFIRMED', 'RETURNED'].includes(item.status)).length ?? 0
  return <div className="page dashboard-page"><PageHeader eyebrow="Operations overview" title="Live store monitor" description="A unified view of the current simulated session, physical evidence, and safe exit decisions." action={<div className="header-actions"><button className="outline-button" onClick={() => navigate('/events')}><ClipboardList size={14} /> Event ledger</button><button className="primary-button" onClick={() => navigate('/simulator')}><Play size={14} fill="currentColor" /> New simulation</button></div>} />
    <div className="status-strip"><div className="status-strip-left"><span className="status-dot green" /><strong>Simulation environment healthy</strong><span>All local providers available</span></div><div className="status-strip-right"><span><Activity size={13} /> 42ms event loop</span><span><Camera size={13} /> 3 / 3 cameras</span><span><Radio size={13} /> 4 / 4 shelves</span></div></div>
    <div className="metric-grid"><MetricCard label="Active sessions" value={active ? '01' : '00'} detail={active ? 'one session in lab' : 'no active simulation'} icon={Users} tone="cyan" /><MetricCard label="Confirmed items" value={String(confirmed).padStart(2, '0')} detail="fusion agreement" icon={CircleCheck} tone="green" trend={confirmed ? '+1' : '0%'} /><MetricCard label="Provisional items" value={String(provisional).padStart(2, '0')} detail="needs evidence" icon={AlertTriangle} tone="amber" /><MetricCard label="Open exceptions" value={String(openExceptions).padStart(2, '0')} detail="review queue" icon={ShieldCheck} tone="purple" /></div>
    {!active ? <div className="dashboard-empty"><div className="overview-card idle-overview"><div className="idle-visual"><div className="idle-ring ring-one" /><div className="idle-ring ring-two" /><div className="idle-core"><Radio size={26} /></div><span className="idle-node node-one" /><span className="idle-node node-two" /><span className="idle-node node-three" /></div><div className="idle-copy"><div className="eyebrow">No session in progress</div><h2>Store telemetry is standing by.</h2><p>Launch a deterministic scenario to watch a customer move through the store and see every evidence stream reconcile at the exit.</p><div className="idle-actions"><button className="primary-button" onClick={() => navigate('/simulator')}><Play size={14} fill="currentColor" /> Start a scenario</button><button className="ghost-button" onClick={() => navigate('/architecture')}>View system map <ArrowRight size={14} /></button></div></div></div><div className="quick-card"><div className="panel-kicker"><Gauge size={13} /> Operator shortcuts</div><button onClick={() => navigate('/simulator')}><span><Timer size={15} /> Resume last simulation</span><ArrowRight size={14} /></button><button onClick={() => navigate('/events')}><span><ClipboardList size={15} /> Browse event ledger</span><ArrowRight size={14} /></button><button onClick={() => setSettings({ debugMode: true })}><span><RefreshCw size={15} /> Enable developer mode</span><ArrowRight size={14} /></button></div></div> : <>
      <div className="dashboard-grid top-grid"><div className="overview-card live-overview"><div className="panel-heading"><div><div className="panel-kicker"><Activity size={13} /> Live store overview</div><h3>{scenario.name}</h3></div><StatusPill status={result?.overallStatus ?? status} small /></div><div className="store-wireframe"><div className="wire-floor" /><div className="wire-shelf ws1"><span>S01</span><i /><i /></div><div className="wire-shelf ws2"><span>S02</span><i /><i /></div><div className="wire-shelf ws3"><span>S03</span><i /><i /></div><div className="wire-customer"><span>01</span></div><div className="wire-path" /><div className="wire-exit">EXIT</div><div className="wire-camera wc1" /><div className="wire-camera wc2" /></div><div className="overview-footer"><div><span>Current action</span><strong>{useSimulationStore.getState().currentAction}</strong></div><div><span>Exit state</span><strong className="cyan-text">{session.exitState.replace('_', ' ')}</strong></div><div><span>Events</span><strong>{events.length}</strong></div></div></div><div className="overview-card session-card"><div className="panel-heading"><div><div className="panel-kicker"><Users size={13} /> Active session</div><h3>{session.id.split('-').slice(-2).join('-')}</h3></div><span className="session-live"><i /> {status}</span></div><div className="session-person"><div className="person-avatar">01</div><div><strong>Customer track · person_01</strong><span>Association confidence {Math.round((result?.confidence ?? 0.96) * 100)}%</span></div></div><div className="session-facts"><div><span>Scenario</span><strong>{scenario.name}</strong></div><div><span>Started</span><strong>{new Date(session.startedAt).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</strong></div><div><span>Provider mode</span><strong>Local deterministic</strong></div></div><button className="outline-button full-width" onClick={() => navigate(`/simulation/${scenario.id}`)}>Open active workspace <ArrowRight size={14} /></button></div></div>
      <div className="dashboard-grid evidence-grid"><div className="overview-card"><CameraFeed /></div><div className="overview-card"><ShelfSensors compact /></div><div className="overview-card"><VirtualCart /></div></div>
      <div className="overview-card timeline-card"><SectionHeading label="Live event stream" detail={`${events.length} immutable events`} action={<button className="text-button" onClick={() => navigate('/events')}>Open ledger <ArrowRight size={13} /></button>} /><EventTimeline compact limit={7} /></div><SimulationControls />
    </>}
    <div className="dashboard-footnote"><ShieldCheck size={14} /><span>Neutral language by design: ShopOnGo highlights unresolved evidence and verification paths; it does not label customers or infer intent.</span></div>
  </div>
}
