import { Clipboard, Download, ExternalLink, FileJson, ListFilter, Search, ShieldCheck, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { PageHeader } from '../components/layout/AppShell'
import { EventTimeline } from '../components/timeline/EventTimeline'
import { useSimulationStore } from '../stores/simulationStore'
import { useEventStore } from '../stores/eventStore'
import { useSettingsStore } from '../stores/settingsStore'
import { clearLocalData } from '../stores/simulationStore'
import { useNavigate } from 'react-router-dom'

export function EventsPage() { const navigate = useNavigate(); const events = useSimulationStore((state) => state.events); const scenario = useSimulationStore((state) => state.scenario); const result = useSimulationStore((state) => state.result); const exportJson = useEventStore((state) => state.exportJson); const [query, setQuery] = useState(''); const [copied, setCopied] = useState(false); const debug = useSettingsStore((state) => state.debugMode); const filteredCount = useMemo(() => query ? events.filter((event) => JSON.stringify(event).toLowerCase().includes(query.toLowerCase())).length : events.length, [events, query]); const copy = () => { navigator.clipboard?.writeText(JSON.stringify(events, null, 2)); setCopied(true); setTimeout(() => setCopied(false), 1400) }; return <div className="page events-page"><PageHeader eyebrow="Audit surface" title="Event ledger" description="Immutable, timestamped evidence emitted by local providers and the fusion engine." action={<div className="header-actions"><button className="outline-button" onClick={copy}><Clipboard size={14} /> {copied ? 'Copied' : 'Copy JSON'}</button><button className="primary-button" onClick={() => exportJson(events)}><Download size={14} /> Export ledger</button></div>} /><div className="ledger-summary"><div><div className="ledger-summary-icon cyan"><FileJson size={17} /></div><div><span>Current stream</span><strong>{events.length} events</strong></div></div><div><div className="ledger-summary-icon green"><ShieldCheck size={17} /></div><div><span>Scenario</span><strong>{scenario.name}</strong></div></div><div><div className="ledger-summary-icon amber"><ListFilter size={17} /></div><div><span>Filtered view</span><strong>{filteredCount} visible</strong></div></div><div><div className="ledger-summary-icon purple"><ExternalLink size={17} /></div><div><span>Fusion output</span><strong>{result?.overallStatus.replaceAll('_', ' ') ?? 'pending'}</strong></div></div></div><div className="ledger-toolbar"><div className="search-field"><Search size={14} /><input placeholder="Search event IDs, products, source, or payload…" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="ledger-toolbar-actions">{debug && <span className="debug-chip">debug fields visible</span>}<button className="text-button" onClick={() => { clearLocalData(); window.location.reload() }}><Trash2 size={13} /> Clear local data</button></div></div>{query ? <QueryTimeline query={query} /> : <div className="ledger-card"><EventTimeline /></div>}<div className="ledger-footer"><span>Source events remain immutable. Reconciliation derives state without rewriting the original evidence.</span><button className="text-button" onClick={() => navigate('/architecture')}>See provider boundaries <ExternalLink size={12} /></button></div></div> }
function QueryTimeline({ query }: { query: string }) { const events = useSimulationStore((state) => state.events); const matched = events.filter((event) => JSON.stringify(event).toLowerCase().includes(query.toLowerCase())); return <div className="ledger-card"><div className="query-results">{matched.length ? matched.map((event) => <div className="query-row" key={event.id}><code>{event.id}</code><strong>{event.type}</strong><span>{event.source}</span><em>{event.productId ?? event.shelfId ?? '—'}</em></div>) : <div className="timeline-empty">No events match this query.</div>}</div></div> }
