import { motion } from 'framer-motion'
import { ArrowRight, Boxes, BrainCircuit, Check, Eye, Layers3, LockKeyhole, Play, ScanLine, ShieldCheck, Sparkles, Workflow } from 'lucide-react'
import { useNavigate } from 'react-router-dom'

export function LandingPage() {
  const navigate = useNavigate()
  return <div className="landing-page"><header className="landing-nav"><div className="brand landing-brand"><div className="brand-mark"><ShieldCheck size={18} /></div><div><div className="brand-name">Shop<span>OnGo</span></div><div className="brand-sub">Intelligent scan-and-go verification</div></div></div><nav><a href="#capabilities">Capabilities</a><a href="#how-it-works">How it works</a><button className="landing-link" onClick={() => navigate('/architecture')}>Architecture <ArrowRight size={14} /></button></nav><button className="outline-button compact-button" onClick={() => navigate('/simulator')}>Open lab <ArrowRight size={14} /></button></header><main>
    <section className="hero-section"><div className="hero-copy"><div className="eyebrow hero-eyebrow"><span className="eyebrow-mark"><Sparkles size={12} /></span> Evidence-first retail orchestration</div><h1>Verify every physical interaction <span>before the customer reaches the exit.</span></h1><p>ShopOnGo simulates how computer vision, mobile scans, and shelf intelligence can work together to reconcile a customer's physical shopping journey.</p><div className="hero-actions"><button className="primary-button" onClick={() => navigate('/simulator')}><Play size={15} fill="currentColor" /> Launch simulation</button><button className="ghost-button" onClick={() => navigate('/architecture')}>Explore architecture <ArrowRight size={15} /></button></div><div className="hero-trust"><span><i className="status-dot green" /> software simulation</span><span><LockKeyhole size={12} /> no real payments</span><span><Eye size={12} /> no facial recognition</span></div></div><div className="hero-visual"><HeroStorePreview /></div></section>
    <section className="stat-ribbon"><div><strong>3</strong><span>evidence streams</span></div><div><strong>13</strong><span>deterministic scenarios</span></div><div><strong>18</strong><span>typed event states</span></div><div><strong>0</strong><span>real customer data</span></div></section>
    <section id="capabilities" className="feature-section"><div className="section-intro"><div className="eyebrow">Built for the ambiguous middle</div><h2>Signals are useful. <span>Evidence is better.</span></h2><p>ShopOnGo keeps declared intent, observed movement, and physical shelf state separate until a transparent fusion layer reconciles them.</p></div><div className="feature-grid"><Feature icon={BrainCircuit} index="01" title="Multi-signal verification" body="Combine mobile scans, camera observations, and physical shelf events without pretending any one signal is perfect." /><Feature icon={ScanLine} index="02" title="Virtual-cart integrity" body="Track declared and physically observed items as separate evidence streams, with confidence visible on every line." /><Feature icon={Workflow} index="03" title="Exception-first design" body="Ambiguous events route to review instead of forcing unsafe automation or making claims about intent." /><Feature icon={Layers3} index="04" title="Extensible architecture" body="Replace simulated providers with OpenCV, WebRTC, hardware sensors, or a FastAPI event bus later." /></div></section>
    <section id="how-it-works" className="flow-section"><div className="flow-copy"><div className="eyebrow">From shelf to gate</div><h2>A small store. A <span>serious control loop.</span></h2><p>Watch a customer move through a low-poly store, inspect the simulated camera feed, and see the reconciliation result form at the exit.</p><button className="outline-button" onClick={() => navigate('/simulation/normal-purchase')}>View normal flow <ArrowRight size={14} /></button></div><div className="flow-steps"><FlowStep n="01" title="Observe" body="Vision and smart shelf providers emit immutable, timestamped events." /><FlowStep n="02" title="Reconcile" body="The fusion engine compares declared and physical evidence." /><FlowStep n="03" title="Resolve" body="The exit gate approves, holds, or creates a human-review exception." /></div></section>
    <section className="landing-disclaimer"><ShieldCheck size={18} /><div><strong>Simulation boundary</strong><p>Current version is a software simulation. It does not claim to detect real theft and does not process real payments.</p></div><button onClick={() => navigate('/limitations')}>Read limitations <ArrowRight size={14} /></button></section>
  </main><footer className="landing-footer"><span>© 2026 ShopOnGo research prototype</span><span>Built for transparent retail systems</span></footer></div>
}
function Feature({ icon: Icon, index, title, body }: { icon: React.ElementType; index: string; title: string; body: string }) { return <div className="feature-card"><div className="feature-top"><div className="feature-icon"><Icon size={17} /></div><span>{index}</span></div><h3>{title}</h3><p>{body}</p><div className="feature-line" /></div> }
function FlowStep({ n, title, body }: { n: string; title: string; body: string }) { return <div className="flow-step"><span>{n}</span><div><strong>{title}</strong><p>{body}</p></div></div> }
function HeroStorePreview() { return <div className="hero-store"><div className="hero-store-glow" /><div className="hero-store-toolbar"><span><i className="status-dot green" /> LIVE MODEL</span><span>CV / SHELF / MOBILE</span></div><div className="mini-store"><div className="mini-wall" /><div className="mini-shelf shelf-a"><i /><i /><i /></div><div className="mini-shelf shelf-b"><i /><i /><i /></div><div className="mini-floor-grid" /><div className="mini-customer"><div className="mini-head" /><div className="mini-body" /><div className="mini-track" /></div><div className="mini-camera cam-a"><span /><b>0.96</b></div><div className="mini-camera cam-b"><span /><b>0.88</b></div><div className="mini-exit"><span /><b>EXIT</b></div><div className="scan-beam" /></div><div className="hero-event event-one"><span className="event-icon cyan"><ScanLine size={12} /></span><div><strong>ITEM_SCANNED</strong><span>Roast coffee · 94%</span></div></div><div className="hero-event event-two"><span className="event-icon green"><Check size={12} /></span><div><strong>FUSION_CONFIRMED</strong><span>3 signals agree</span></div></div><div className="hero-visual-footer"><span><i /> customer track</span><span><i /> shelf baseline</span><span><i /> camera zone</span></div></div> }
