import { ArrowRight, CheckCircle2, Clock3, Layers3, Play, ShieldAlert, SlidersHorizontal, Sparkles, TriangleAlert, Zap } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useState } from 'react'
import { PageHeader } from '../components/layout/AppShell'
import { scenarios } from '../data/scenarios'
import { useSimulationStore } from '../stores/simulationStore'
import { StatusPill } from '../components/common/StatusPill'
import { Toggle } from '../components/common/Toggle'
import { useSettingsStore } from '../stores/settingsStore'

const categoryLabel = { NORMAL: 'baseline', DISCREPANCY: 'discrepancy', FAILURE: 'failure', EDGE_CASE: 'edge case' }
export function SimulatorPage() {
  const navigate = useNavigate(); const launch = useSimulationStore((state) => state.launchScenario); const [category, setCategory] = useState<'ALL' | keyof typeof categoryLabel>('ALL'); const settings = useSettingsStore(); const filtered = scenarios.filter((scenario) => category === 'ALL' || scenario.category === category)
  const choose = (id: string) => { launch(id); navigate(`/simulation/${id}`) }
  return <div className="page simulator-page"><PageHeader eyebrow="Scenario lab" title="Choose a verification journey" description="Every run is deterministic, replayable, and built from the same provider boundaries as a future production system." action={<div className="lab-summary"><span><i className="status-dot cyan" /> providers ready</span><span><i className="status-dot green" /> local only</span></div>} />
    <div className="scenario-toolbar"><div className="category-tabs">{(['ALL', 'NORMAL', 'DISCREPANCY', 'FAILURE', 'EDGE_CASE'] as const).map((item) => <button className={category === item ? 'active' : ''} key={item} onClick={() => setCategory(item)}>{item === 'ALL' ? 'All journeys' : categoryLabel[item]}</button>)}</div><div className="toolbar-controls"><span><Layers3 size={13} /> 13 scenarios</span><button className="icon-button" title="Open developer settings" onClick={() => settings.set({ debugMode: !settings.debugMode })}><SlidersHorizontal size={15} /></button></div></div>
    <div className="scenario-grid">{filtered.map((scenario, index) => <ScenarioCard key={scenario.id} scenario={scenario} index={index} onLaunch={choose} />)}</div>
    <div className="scenario-note"><Sparkles size={16} /><div><strong>How to read the results</strong><p>Physical observation, mobile declaration, and shelf state remain separate evidence streams. An unresolved result means verification is required — not that the system knows a customer's intent.</p></div><button className="text-button" onClick={() => navigate('/limitations')}>Read assumptions <ArrowRight size={13} /></button></div>
    <div className="settings-strip"><div><div className="panel-kicker"><SlidersHorizontal size={13} /> Demo settings</div><strong>Adjust the evidence surface before launch.</strong></div><div className="settings-inline"><Toggle label="Reduced motion" value={settings.reducedMotion} onChange={(value) => settings.set({ reducedMotion: value })} /><Toggle label="Low performance" value={settings.lowPerformance} onChange={(value) => settings.set({ lowPerformance: value })} /><Toggle label="Developer mode" value={settings.debugMode} onChange={(value) => settings.set({ debugMode: value })} /></div></div>
  </div>
}
function ScenarioCard({ scenario, index, onLaunch }: { scenario: typeof scenarios[number]; index: number; onLaunch: (id: string) => void }) { const Icon = scenario.category === 'NORMAL' ? CheckCircle2 : scenario.category === 'FAILURE' ? TriangleAlert : scenario.category === 'EDGE_CASE' ? Zap : ShieldAlert; return <article className={`scenario-card ${scenario.category.toLowerCase()}`}><div className="scenario-card-top"><div className="scenario-number">{String(index + 1).padStart(2, '0')}</div><div className="scenario-icon"><Icon size={16} /></div><StatusPill status={scenario.risk === 'LOW' ? 'CONFIRMED' : scenario.risk === 'MEDIUM' ? 'PROVISIONAL' : 'EXCEPTION_REQUIRED'} small /></div><div className="scenario-card-body"><div className="scenario-category">{categoryLabel[scenario.category]} · {scenario.risk} risk</div><h3>{scenario.name}</h3><p>{scenario.description}</p><div className="scenario-meta"><span><Clock3 size={12} /> {scenario.durationSeconds}s</span><span><Zap size={12} /> {scenario.eventsCount} events</span></div></div><div className="scenario-outcome"><span>Expected outcome</span><strong>{scenario.expectedOutcome}</strong></div><button className="scenario-launch" onClick={() => onLaunch(scenario.id)}>Launch journey <Play size={13} fill="currentColor" /></button></article> }
