import { Maximize2, Pause, Play, ScanLine, Target, Video, VideoOff } from 'lucide-react'
import { useState } from 'react'
import { useSceneStore } from '../../stores/sceneStore'
import { useSettingsStore } from '../../stores/settingsStore'
import { useSimulationStore } from '../../stores/simulationStore'

export function CameraFeed() {
  const [playing, setPlaying] = useState(true)
  const cameraMode = useSceneStore((state) => state.cameraMode)
  const setCameraMode = useSceneStore((state) => state.setCameraMode)
  const { overlay, boundingBoxes, confidence } = useSettingsStore((state) => state)
  const setSettings = useSettingsStore((state) => state.set)
  const events = useSimulationStore((state) => state.events)
  const latestVision = [...events].reverse().find((event) => event.source === 'VISION_SIMULATOR')
  const uncertain = latestVision?.type === 'CAMERA_UNCERTAIN' || (latestVision?.confidence ?? 1) < 0.65
  const cameraName = cameraMode === 'CAMERA_01' ? 'Camera 01 · Entry' : cameraMode === 'CAMERA_02' ? 'Camera 02 · Aisle' : cameraMode === 'EXIT_CAMERA' ? 'Camera 03 · Exit' : 'Camera 02 · Aisle'
  const action = latestVision?.type === 'ITEM_MOVED_TO_BAG' ? 'ITEM UNOBSERVABLE' : latestVision?.type === 'CAMERA_PICK_DETECTED' ? 'PICK' : uncertain ? 'UNCERTAIN' : 'TRACKING'
  return <div className="camera-panel"><div className="panel-heading"><div><div className="panel-kicker"><Video size={13} /> Computer vision feed</div><h3>{cameraName}</h3></div><span className="live-tag"><i /> SIMULATED CV</span></div><div className="camera-viewport"><div className="camera-grid" /><div className="camera-floor-line" /><div className={`camera-person ${uncertain ? 'uncertain' : ''}`}><div className="camera-head" /><div className="camera-body" /><div className="camera-trail" /></div>{boundingBoxes && <><div className={`bbox person ${uncertain ? 'uncertain' : ''}`}><span>person_01</span></div><div className={`bbox product ${action === 'UNCERTAIN' ? 'uncertain' : action === 'ITEM UNOBSERVABLE' ? 'warning' : 'confirmed'}`}><span>{action}</span></div></>}{overlay && <div className="camera-overlay-corners"><span>ZONE: {latestVision?.shelfId ?? 'entry'}</span><span>ACTION: {action}</span></div>}<div className="camera-timestamp">{new Date().toLocaleTimeString('en-IN', { hour12: false })}.042 · 18 FPS</div><div className={`camera-scanline ${playing ? 'moving' : ''}`} /></div><div className="camera-controls"><select value={cameraMode === 'OPERATOR' ? 'CAMERA_02' : cameraMode} onChange={(event) => setCameraMode(event.target.value as typeof cameraMode)} aria-label="Select camera feed"><option value="CAMERA_01">Camera 01 · Entry</option><option value="CAMERA_02">Camera 02 · Aisle</option><option value="EXIT_CAMERA">Camera 03 · Exit</option></select><button className="icon-button" aria-label={playing ? 'Pause camera feed' : 'Play camera feed'} onClick={() => setPlaying(!playing)}>{playing ? <Pause size={14} /> : <Play size={14} />}</button><button className="icon-button" aria-label="Toggle overlays" onClick={() => setSettings({ overlay: !overlay })}><Target size={14} /></button><button className="icon-button" aria-label="Fullscreen camera feed"><Maximize2 size={14} /></button></div><div className="camera-toggles"><button className={overlay ? 'on' : ''} onClick={() => setSettings({ overlay: !overlay })}>{overlay ? <Video size={12} /> : <VideoOff size={12} />} overlay</button><button className={boundingBoxes ? 'on' : ''} onClick={() => setSettings({ boundingBoxes: !boundingBoxes })}><span className="box-icon" /> boxes</button><button className={confidence ? 'on' : ''} onClick={() => setSettings({ confidence: !confidence })}>confidence</button></div>{confidence && <div className="confidence-strip"><span>PERSON <b>{Math.round((latestVision?.confidence ?? 0.96) * 100)}%</b></span><span>INTERACTION <b>{Math.round((latestVision?.confidence ?? 0.88) * 100)}%</b></span><span>PRODUCT <b>{Math.round((latestVision?.confidence ?? 0.82) * 100)}%</b></span></div>}</div>
}
